language: node_js
node_js:
  - "0.12"
  - "0.10"

addons:
    apt:
        packages:
            - libcairo2-dev
            - libjpeg8-dev
            - libpango1.0-dev
            - libgif-dev
            - build-essential
            - g++

before_script: npm install -g istanbul
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec tests/index.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

after_success:
  - npm run coverage-istanbul
  - npm run report-coverage
